const getLanguageFromExtension = (fileName: string): string => {
  const ext = fileName.split('.').pop()?.toLowerCase();

  switch (ext) {
    case 'js':
    case 'mjs':
    case 'cjs':
      return 'javascript';
    case 'jsx':
      return 'javascriptreact';
    case 'ts':
      return 'typescript';
    case 'tsx':
      return 'typescriptreact';
    case 'json':
    case 'jsonc':
      return 'json';
    case 'html':
    case 'htm':
      return 'html';
    case 'css':
      return 'css';
    case 'scss':
      return 'scss';
    case 'sass':
      return 'sass';
    case 'less':
      return 'less';
    case 'md':
    case 'markdown':
      return 'markdown';
    case 'txt':
      return 'plaintext';
    case 'yml':
    case 'yaml':
      return 'yaml';
    case 'xml':
      return 'xml';
    case 'php':
      return 'php';
    case 'py':
      return 'python';
    case 'rb':
      return 'ruby';
    case 'java':
      return 'java';
    case 'kt':
    case 'kts':
      return 'kotlin';
    case 'swift':
      return 'swift';
    case 'go':
      return 'go';
    case 'rs':
      return 'rust';
    case 'cpp':
    case 'cc':
    case 'cxx':
    case 'hpp':
    case 'hh':
    case 'hxx':
      return 'cpp';
    case 'c':
    case 'h':
      return 'c';
    case 'sh':
    case 'bash':
    case 'zsh':
      return 'shell';
    case 'bat':
    case 'cmd':
      return 'bat';
    case 'ps1':
      return 'powershell';
    case 'sql':
      return 'sql';
    case 'r':
      return 'r';
    case 'lua':
      return 'lua';
    case 'dart':
      return 'dart';
    case 'scala':
      return 'scala';
    case 'coffee':
      return 'coffeescript';
    case 'ini':
      return 'ini';
    case 'toml':
      return 'toml';
    case 'make':
    case 'mk':
    case 'makefile':
      return 'makefile';
    case 'dockerfile':
    case 'docker':
      return 'dockerfile';
    case 'gradle':
      return 'gradle';
    case 'groovy':
      return 'groovy';
    case 'vb':
      return 'vb';
    case 'cs':
      return 'csharp';
    case 'fs':
      return 'fsharp';
    case 'asm':
    case 's':
      return 'asm';
    case 'tex':
      return 'latex';
    case 'log':
      return 'log';
    case 'env':
      return 'dotenv';
    case 'config':
      return 'properties';

    default:
      return 'plaintext';
  }
};

export default getLanguageFromExtension;
